name: AprilsArt
favicon: null
layout_spectrum: 0.5613330407068133
typography_spectrum: 0.12184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000002'
    - '#b4b4b4'
    - '#5e5643'
    - '#7d7b80'
  brandStrength: 0.8892457040492445
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
