name: AprilsArt
favicon: null
layout_spectrum: 0.5613330407068133
typography_spectrum: 0.12184
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#9c87d4'
    - '#3e5600'
    - '#e2e9fd'
    - '#eea000'
  brandStrength: 0.8892457040492445
  lightness: 0.0613054190762341
  saturation: 0.28335908940061927
  rhythmicContrast: 0.7760316669009626
purpose: []
